### Get all contacts (Local)
GET http://localhost:3000/contacts

### Get single contact (Local) 
GET http://localhost:3000/contacts/69125d90e0f0401a81471393

###

### Get all contacts (Production)
GET https://cse341-contacts-r5qz.onrender.com/contacts

### Get single contact (Production) - Replace ID
GET https://cse341-contacts-r5qz.onrender.com/contacts/69125d90e0f0401a81471393

### GitHub
https://github.com/brucemel/cse341-contacts

### Youtube Video
https://youtu.be/PLYH2mvw5ks