### Get all contacts (Local)
GET http://localhost:3000/contacts

### Get single contact (Local) 
GET http://localhost:3000/contacts/69125d9ce0f0401a81471395

### create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "John Jordan",
  "lastName": "Doe",
  "email": "johnJordan.doe@email.com",
  "favoriteColor": "BlueSky",
  "birthday": "1998-05-15"
}

### PUT contact
PUT http://localhost:3000/contacts/69125d9ce0f0401a81471395 HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@email.com",
  "favoriteColor": "Blue",
  "birthday": "1990-05-15"
}

###delete
DELETE http://localhost:3000/contacts/6918dcfed715f312dcffb127 HTTP/1.1

###

### Get all contacts (Production)
GET https://cse341-contacts-r5qz.onrender.com/contacts

### Get single contact (Production) - Replace ID
GET https://cse341-contacts-r5qz.onrender.com/contacts/69125d90e0f0401a81471393

### GitHub
https://github.com/brucemel/cse341-contacts

### Youtube Video
https://youtu.be/PLYH2mvw5ks